#
# Mongrel Cluster
#
user: deploy
group: deploy
cwd: /var/www/suoc/current
port: "9300"
environment: production
address: 0.0.0.0
pid_file: "/var/run/mongrel_cluster/suoc.pid"
log_file: "log/mongrel.log"
servers: 3

